MoscowWeather.Host/Models/ErrorViewModel.cs
namespace MoscowWeather.Host.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MoscowWeather.Host/Models/ImportArchivesModel.cs
namespace MoscowWeather.Host.Models;

public class ImportArchivesModel
{
    public string? ErrorMessage { get; private set; }
    public bool Success { get; private set; }

    public static ImportArchivesModel SuccessAction() => new ImportArchivesModel() { Success = true };
    public static ImportArchivesModel Error(string message) => new ImportArchivesModel() { ErrorMessage = message };
}

MoscowWeather.Host/Models/ViewArchivesModel.cs
using MoscowWeather.Host.Dtos;

namespace MoscowWeather.Host.Models;

public class ViewArchivesModel
{
    public PaginatedResult<WeatherLogDto> Result { get; set; }
    public List<int> Years { get; set; }
    public QueryFilter Query { get; set; } = new();
}

public class QueryFilter
{
	public QueryFilter(int page, int? year, int? month)
	{
		Page = page;
		Year = year;
		Month = month;
	}
    public QueryFilter()
    {
    }
    public int Page { get; set; } = 1;
    public int? Year { get; set; }
    public int? Month { get; set; }
}

MoscowWeather.Host/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MoscowWeather.Host.Models;
using System.Diagnostics;

namespace MoscowWeather.Host.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MoscowWeather.Host/Controllers/ImportArchivesController.cs
using Microsoft.AspNetCore.Mvc;
using MoscowWeather.Host.Contracts;
using MoscowWeather.Host.Models;

namespace MoscowWeather.Host.Controllers;

public class ImportArchivesController : Controller
{
    private readonly IDataExtractService _dataExtractService;
    private readonly ILogger<ImportArchivesController> _logger;
    private readonly IWeatherRepository _weatherRepository;

    public ImportArchivesController(
        IDataExtractService importService, 
        ILogger<ImportArchivesController> logger, 
        IWeatherRepository weatherRepository)
    {
        _dataExtractService = importService;
        _logger = logger;
        _weatherRepository = weatherRepository;
    }
    public IActionResult Index()
    {
        return View(new ImportArchivesModel());
    }

    public async Task<IActionResult> ImportData([FromForm] List<IFormFile> files)
    {
        try
        {
            foreach (IFormFile file in files)
            {
                if(!string.Equals(Path.GetExtension(file.FileName), ".xlsx", StringComparison.OrdinalIgnoreCase))
					return View("Index", ImportArchivesModel.Error("Only .xlsx files available!"));
				using (var stream = file.OpenReadStream())
                {
                    var logs = _dataExtractService.GetData(stream);
                    if(logs.Any())
                        await _weatherRepository.CreateAsync(logs);
                }
            }
            
            return View("Index",ImportArchivesModel.SuccessAction());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return View("Index", ImportArchivesModel.Error(ex.Message));
        }
        
    }
}

MoscowWeather.Host/Controllers/ViewArchivesController.cs
using Microsoft.AspNetCore.Mvc;
using MoscowWeather.Host.Contracts;
using MoscowWeather.Host.Models;

namespace MoscowWeather.Host.Controllers;

public class ViewArchivesController : Controller
{
    private readonly IWeatherRepository _weatherRepository;

    public ViewArchivesController(IWeatherRepository weatherRepository)
    {
        _weatherRepository = weatherRepository;
    }

    public async Task<IActionResult> Index()
    {
        var logsResult = await _weatherRepository.GetAsync(null, null, 1, 10);
        var years = await _weatherRepository.GetTotalYearsAsync();
        return View(new ViewArchivesModel() { Result = logsResult, Years = years });
    }

    public async Task<IActionResult> GetData(int? year, int? month, int page)
    {
        var logsResult = await _weatherRepository.GetAsync(year, month, page, 10);
		var years = await _weatherRepository.GetTotalYearsAsync();
        return View("Index", new ViewArchivesModel() { Result = logsResult, Years = years, Query = new(page, year, month) });
	}
}

MoscowWeather.Host/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="d-flex flex-column text-center align-items-center gap-2">
    <h1 class="display-4">Погода в Москве</h1>
    <a class="btn btn-outline-primary" asp-controller="ImportArchives" asp-action="Index">Загрузка архивов</a>
    <a class="btn btn-outline-primary" asp-controller="ViewArchives" asp-action="Index">Просмотр архивов</a>
</div>

MoscowWeather.Host/Views/ImportArchives/Index.cshtml
@model ImportArchivesModel
<form 
    method="post" 
    class="d-flex flex-column align-items-center gap-4" 
    enctype="multipart/form-data" 
    id="submitForm"
    action="@Url.Action("ImportData", "ImportArchives")">
    <div class="mt-3">
        <label for="formFile" class="form-label">Выбрать файлы</label>
        <input class="form-control" name="files" accept=".xlsx" type="file" id="formFile" multiple>
    </div>
    <button type="submit" id="submitButton" class="btn btn-primary">Загрузить</button>
</form>
<script>
        document.getElementById("submitForm").addEventListener("submit", function () {
            document.getElementById("submitButton").disabled = true;
            document.getElementById("submitButton").classList.add("btn-disabled");
        });
</script>
@if (Model.ErrorMessage != null)
{
    <div class="border rounded-2 p-2 mt-2 border-danger">Error: @Model.ErrorMessage</div>
}
@if (Model.Success)
{
    <div class="border rounded-2 p-2 mt-2 border-success">Успешно загружено!</div>
}

MoscowWeather.Host/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoscowWeather.Host</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoscowWeather.Host.styles.css" asp-append-version="true" />
</head>
<body>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MoscowWeather.Host - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>